### ISSUE TITLE
Unhandled event loop exception and Editor could not be initialized in LibreOffice Extension Java Eclipse project

### ISSUE THREAD

**Issue by IOException722** [smehrbrodt/libreoffice-starter-extension#1]
While running the this sample program its showing following error.

Unhandled event loop exception and Editor could not be initialized in LibreOffice Extension Java Eclipse
project

**Comment by smehrbrodt** [comment]
This looks like an issue in https://github.com/LibreOffice/loeclipse/ . Could you please file an issue there and post a backtrace if you can get one?

**Comment by IOException722** [comment]
It got solved when I ran a new configuration with LibreOffice Application instead LibreOffice Extension.
Now its running well.
