### ISSUE TITLE
Can't include external jar

### ISSUE THREAD

**Issue by bibiwan** [smehrbrodt/libreoffice-starter-extension#5]
I'm not sure that it's an issue, but I don't know where to ask for help.

I have two problems that I can't explain, even using Eclipse debugger:
When a method from ActionOneDialog class calls an object from another package (in my case, a class from example.comp package), I get a noclassdeffounderror. 

Same problem when a method calls an object from a jar library (I have put it manually in build directory, which I can see in jar file inside oxt after build step, and I declared it as an external jar in Eclipse's build path).

Do I need to declare every classes used by your classes ? If so, where ?
Do I need to declare every library used un my program ? If so, where in Eclipse?

**Comment by smehrbrodt** [comment]
Did you add the jar to your package.properties file?

**Comment by bibiwan** [comment]
Ok, I added my jar into a lib directory, added it as library in my eclipse project, and added it to package.properties... 

It seems to work ! 

Thanks a lot.

**Comment by smehrbrodt** [comment]
Good to hear!
I updated the README to include a note on this.
Let me know if you have any other issues!
